Error: [[react-beautiful-dnd
]A setup problem was encountered.

> Invariant failed: ignoreContainerClipping must be a boolean

👷‍ This is a development only message. It will be removed in production builds.
    at createUnhandledError (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:879:71)
    at handleClientError (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1052:56)
    at console.error (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_client_43e3ffb8._.js:1191:56)
    at log (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_react-beautiful-dnd_dist_react-beautiful-dnd_esm_d54df031.js:66:32)
    at useDevSetupWarning.useDev.useEffect (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_react-beautiful-dnd_dist_react-beautiful-dnd_esm_d54df031.js:4622:25)
    at connectAdvanced.wrapWithConnect.ConnectFunction.useMemo[renderedWrappedComponent] (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_36533b0a._.js:14947:211)
    at mountMemo (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:6205:25)
    at Object.useMemo (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:14956:24)
    at exports.useMemo (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_compiled_2ce9398a._.js:1672:36)
    at ConnectFunction (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_36533b0a._.js:14945:217)
    at KanbanColumn (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/src_81bd9af9._.js:3219:215)
    at https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/src_81bd9af9._.js:3682:245
    at Array.map (<anonymous>)
    at KanbanBoard (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/src_81bd9af9._.js:3680:173)
    at ProjectPage (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/src_81bd9af9._.js:5698:239)
    at ClientPageRoot (https://6000-firebase-studio-1748521280730.cluster-ubrd2huk7jh6otbgyei4h62ope.cloudworkstations.dev/_next/static/chunks/node_modules_next_dist_1a6ee436._.js:2053:50)